### PR TITLE
v3.0.0

### PR DESCRIPTION
**Pull request by adamant-al**

### CODE REVIEW

**Comment by adamant-al** [comment]
Mobile version should take all the screen width, not more, not less
See https://i.imgur.com/asLlQfT.png

**Comment by adamant-al** [comment]
https://i.imgur.com/VQFQxav.png

- "Forged this period" value is wrong. Expected: 0.
- App don't show voters if status is Standby. Expected to see current voters.
- Show delegate name without quotes, but **bold** style and should link to explorer like https://explorer.adamant.im/delegate/U9466395914658764774 in new tab
- Expected to see Productivity
- "donates 1.5% to ADAMANT Foundation" instead of "donates 1.5"
- Use favicon from previous version
- Github link should target this repository

**Comment by adamant-al** [comment]
Add favicons and tiles from previous version

**Comment by adamant-al** [comment]
@martiliones

**Comment by martiliones** [comment]
the tables from ui library I used are breaking layout in chrome browser, but in Firefox everything seems to be okay

I will try to write own realisation of the ui elements today and drop the library from dependencies

**Comment by martiliones** [comment]
Productivity is not shown for delegates with rank higher than 101 like in the past versions of ADAMANT Pool

**Comment by martiliones** [comment]
other problems can be fixed in under 5 minutes

**Comment by adamant-al** [comment]
> the tables from ui library I used are breaking layout in chrome browser, but in Firefox everything seems to be okay
> 
> I will try to write own realisation of the ui elements today and drop the library from dependencies

It's important to support all of modern browsers.

> https://i.imgur.com/VQFQxav.png

There is no place for Productivity. If delegate has no Productivity, show dash `—`

**Comment by martiliones** [comment]
> There is no place for Productivity

Productivity is displayed instead of status according to the code from pool v2: 

```vue
<div v-if="delegate.delegate.rank <= 101">Productivity: {{delegate.delegate.productivity}}%
</div>
<div v-else style="color: darkred;">Status: Standby</div>
```

I will add one more column in the 2nd row to separate them

**Comment by adamant-al** [comment]
> > There is no place for Productivity
> 
> Productivity is displayed instead of status according to the code from pool v2:
> 
> ```
> <div v-if="delegate.delegate.rank <= 101">Productivity: {{delegate.delegate.productivity}}%
> </div>
> <div v-else style="color: darkred;">Status: Standby</div>
> ```
> 
> I will add one more column in the 2nd row to separate them

It's OK then, no changes here.

**Comment by adamant-al** [comment]
- App doesn't show voters if status is Standby. Expected to see current voters.
- It seems favicons and tiles paths are wrong. Console shows `GET http://localhost:36667/assets/icons/apple-touch-icon-152x152.png 404 (Not Found)`
- I don't see `db` folder. Shouldn't it store processed blocks?
- A script to update database from v2
- pm2 shows wrong version 0.39.1. Expected to see 3.0.0. https://i.imgur.com/lkag9cn.png
- Turn on web autoupdate every 1 minute

**Comment by adamant-al** [comment]
@martiliones Are you still in Trello?

**Comment by adamant-al** [comment]
- `warn|…  Failed to save block…`
- `error|…  Pool …: Rewards on block … could not be distributed. Failed to add voter U1695629837421250761`
- `error|…  Failed to update rewards for …`

**Comment by martiliones** [comment]
@adamant-al 

1. `db` folder should be located inside `server/` directory
2. pm2 shows wrong version when using `nvm`, I can add shell script to run the app from it

**Comment by adamant-al** [comment]
> @adamant-al
> 
> 1. `db` folder should be located inside `server/` directory
> 2. pm2 shows wrong version when using `nvm`, I can add shell script to run the app from it

1. I don't see it neither on GitHub, nor on production: https://i.imgur.com/UyzcABP.png and https://i.imgur.com/Cr1xtBo.png
2. If there is no other fix, yes, and a script that will show correct version with pm2

**Comment by adamant-al** [comment]
https://i.imgur.com/f7jklLI.png

- Autoupdate doesn't work (watch a web page)
- "Forged this period" is wrong
- "Pending rewards" is wrong
- App don't show voters if status is Standby. Expected to see current voters. https://i.imgur.com/RLoOcad.png
- Want a script to update database from v2
- `cd server` && `npm run test dev` shows many errors
- Update dependencies

**Comment by adamant-al** [comment]
- fix `npm run build:web`: `Security: Anchor with "target=_blank" should have rel attribute containing the value "noreferrer"`
- should we remove `author`, `licence`, `keywords`, links.. in `/server/package.json`?
- should we remove `/web/README.md`?
- Update Readme. There is still `adamant-pool`, but expected `pool` repository name
- The pool don't count and distribute rewards to ADAMANT Foundation U380651761819723095 and maintenance wallet. I see a message: `Pool's share 0.0000 ADM (10.00%) is less, than Tx fee.`. Expected like this: `..Sent 3.6022 ADM (10.00%) pool's share to maintenance wallet U12345677. Sent 21.6133 ADM (20.00%) donation to U380651761819723095.`
- Other message is wrong: `..This period the pool forged 0.0000 ADM from 0 blocks; 0.0000 ADM distributed to users.`
- Update client app deps. `web % ncu`
Checking /Users/Das/Work/adamant.im/Dev/Pool-v3/pool/web/package.json
[====================] 11/11 100%

 @sveltejs/vite-plugin-svelte   ^1.4.0  →   ^2.0.2
 svelte                        ^3.53.1  →  ^3.55.0
 vite                           ^3.2.5  →   ^4.0.1
 vite-plugin-windicss           ^1.8.8  →  ^1.8.10

**Comment by adamant-al** [comment]
Have you finished with all the tasks? 
Enable the pool's notifications to test.

**Review by dev-adamant-im — APPROVED** [review]

**Pull request merged**
